services:
    breithbarbot.cropper.cropper_type:
        class: Breithbarbot\CropperBundle\Form\Type\CropperType
        tags:
            - { name: form.type, alias: cropper }
        arguments: ['%breithbarbot_cropper.data_class%']

    breithbarbot.cropper.cropper_extension:
        class: Breithbarbot\CropperBundle\Twig\Extension\CropperExtension
        tags:
            - { name: twig.extension }
        arguments: ['@assets.packages']
