services:
    breithbarbot.cropper.form.type.cropper:
        class: Breithbarbot\CropperBundle\Form\Type\CropperType
        tags:
            - { name: form.type, alias: cropper }
        arguments: ['%breithbarbot_cropper.data_class%', '@service_container']

    breithbarbot.cropper.twig.extension.asset:
        class: Breithbarbot\CropperBundle\Twig\Extension\AssetExtension
        tags:
            - { name: twig.extension }
        arguments: ['@assets.packages']

    breithbarbot.cropper.twig.extension.parameter:
        class: Breithbarbot\CropperBundle\Twig\Extension\ParameterExtension
        tags:
          - { name: twig.extension }
        arguments: ['@service_container']
